apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  name: aw-batch-1
  namespace: default
  #new addition
  labels:
    orderedinstance: "m5.4xlarge_g4dn.xlarge"
spec:
  priority: 9
  resources:
    Items: []
    GenericItems:
    - replicas: 1
      custompodresources:
      - replicas: 1
        requests:
          cpu: 2
          memory: 12G
          nvidia.com/gpu: 0
        limits:
          cpu: 2
          memory: 12G
          nvidia.com/gpu: 0
      generictemplate:
        apiVersion: batch/v1
        kind: Job
        metadata:
          namespace: default
          name: aw-batch-1-1
          # labels:
          #   appwrapper.mcad.ibm.com: aw-batch-1
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              namespace: default
              labels:
                appwrapper.mcad.ibm.com: "aw-batch-1"
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: aw-batch-1
                        operator: In
                        values:
                        - aw-batch-1
              containers:
              - name: aw-batch-1-1
                image: ubuntu:latest
                command: [ "/bin/bash", "-c", "--" ]
                args: [ "sleep infinity" ]
                resources:
                  requests:
                    memory: 11G
                    cpu: 2
                  limits:
                    memory: 11G
                    cpu: 2
              restartPolicy: Never
    - replicas: 1
      custompodresources:
      - replicas: 1
        requests:
          cpu: 2
          memory: 12G
          nvidia.com/gpu: 1
        limits:
          cpu: 2
          memory: 12G
          nvidia.com/gpu: 1
      generictemplate:
        apiVersion: batch/v1
        kind: Job
        metadata:
          namespace: default
          name: aw-batch-1-2
          # labels:
          #   appwrapper.mcad.ibm.com: aw-batch-1
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              namespace: default
              labels:
                appwrapper.mcad.ibm.com: "aw-batch-1"
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: aw-batch-1
                        operator: In
                        values:
                        - aw-batch-1
              containers:
              - name: aw-batch-1-2
                image: ubuntu:latest
                command: [ "/bin/bash", "-c", "--" ]
                args: [ "sleep infinity" ]
                resources:
                  requests:
                    memory: 11G
                    cpu: 2
                    nvidia.com/gpu: 1
                  limits:
                    memory: 11G
                    cpu: 2
                    nvidia.com/gpu: 1
              restartPolicy: Never